### ISSUE TITLE
Language is broken.

### ISSUE THREAD

**Issue by ghost** [MadHed/strela#4]
@sunverwerth 

```
mymax% Release/strela file.strela
zsh: segmentation fault  Release/strela file.strela
```

I don't know how to fix this.

**OS:** macOS x86_64

Core library installed, my steps:

```
make
make install
Release/strela file.strela
```

**file.strela:**

```
module Hello {
    import Std.IO.println;

    function main(): int {
        println("Hello, world!");
        return 0;
    }
}
```

**Comment by t0md3an** [comment]
@sunverwerth I will try to debug it.

I found your project while looking for interesting and non-standard programming languages on github.

**Comment by t0md3an** [comment]
@sunverwerth debug version of Strela gave me only this:

```
Segmentation fault  Debug/strela file.strela
```

**Comment by sunverwerth** [comment]
I ran this in the debugger myself, here's the fix:
You need to pass arguments array to main: `function main(args: String[]): int`

I never got around to check the signature of main() it crashes when trying to allocate memory for the non-existing arguments array.

**Comment by t0md3an** [comment]
@sunverwerth Ok, now it works fine. But I have another question. How to compile it to `a.out`?

**Comment by sunverwerth** [comment]
Compilation to machine code is not supported currently. It's only interpreted.

**Comment by sunverwerth** [comment]
@t0md3an I've added a check for this situation. Thanks for the report 👍
